### ISSUE TITLE
Sclipting interpreter is only found here; not portable

### ISSUE THREAD

**Issue by nickbclifford** [Timwi/EsotericIDE#8]
Recently, I've been getting very interesting in [Sclipting](esolangs.org/wiki/Sclipting). However, when I tried to find an interpreter for my Linux box, I was stuck, since the only interpreter that I can find exists in this Windows Forms application.

Is there a way to possibly create an independent interpreter or at least somehow separate it from Windows Forms so I can compile it with Mono or something?

**Comment by Timwi** [comment]
Esoteric IDE worked fine in Mono on Linux when I tried it. Mono does implement Windows Forms. If you find it not working for you, try to determine whether the problem is with Esoteric IDE or with Mono and then file an appropriate specific bugreport in the correct place.

If you wish to decouple the interpreter from the IDE, you are the free to do so yourself. The code is open-source and free under the MIT licence.
